# ==========================================
# CONEXÃO COM O BANCO DE DADOS (PostgreSQL)
# ==========================================
# LÊ A VARIÁVEL DO DOCKER PRIMEIRO! Se não achar, usa localhost.
spring.datasource.url=${DB_CUD_URL:jdbc:postgresql://localhost:5432/bantads_db}
spring.datasource.username=${DB_USERNAME:springuser}
spring.datasource.password=${DB_PASSWORD:password}

# Resolve o erro do "Dialect" avisando pro Spring que é PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações de criação e inserts (data.sql)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ==========================================
# CONEXÃO COM A FILA DE MENSAGENS (RabbitMQ)
# ==========================================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest