spring.application.name=ms-cliente
server.port=8082

spring.datasource.url=jdbc:postgresql://postgres-cliente:5432/bantads_cliente?currentSchema=ms_clientespring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=ms_cliente
spring.jpa.show-sql=true