spring.application.name=ms-cliente
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bantads_db?currentSchema=ms_cliente}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:springuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true