spring.application.name=gerente
server.port=8083

# ===== PostgreSQL =====
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/bantads_gerente}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:springuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=ms_gerente

# ===== SQL Init =====
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=true

# ===== Swagger =====
springdoc.swagger-ui.path=/swagger-ui.html
