aplicacao.datasource.escrita.url=${DB_CUD_URL:jdbc:postgresql://localhost:5432/bantads_db}
aplicacao.datasource.escrita.username=${DB_USERNAME:springuser}
aplicacao.datasource.escrita.password=${DB_PASSWORD:password}
aplicacao.datasource.escrita.driver-class-name=org.postgresql.Driver

aplicacao.datasource.leitura.url=${DB_READ_URL:${DB_CUD_URL:jdbc:postgresql://localhost:5432/bantads_db}}
aplicacao.datasource.leitura.username=${DB_USERNAME:springuser}
aplicacao.datasource.leitura.password=${DB_PASSWORD:password}
aplicacao.datasource.leitura.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
